### ISSUE TITLE
Release for Spigot 1.9

### ISSUE THREAD

**Issue by ghost** [DevotedMC/WorldBorder#1]
Hi
Can you build a release version for Spigot 1.9?

**Comment by ProgrammerDan** [comment]
Hey friend,

If you check here: http://dev.bukkit.org/bukkit-plugins/worldborder/ there is a build from the main line trunk. 

If you're looking for any of the customizations that I've made, let me know, I can definitely put up a build.

**Comment by ghost** [comment]
It s not made for Spigot 1.9
`
<dependency>
<groupId>org.spigotmc</groupId>
<artifactId>spigot-api</artifactId>
<version>1.8.7-R0.1-SNAPSHOT</version>
</dependency>
`
Can you give me a build of yours that support Spigot 1.9

**Comment by ProgrammerDan** [comment]
That's just the API level -- it's still API compatible with 1.9.x, and most likely compatible with 1.10 as well.

The only time the dependency matters is if it's not `spigot-api` -- but assuming it's just against the API it's generally compatible at that release level and after. Some exceptions exist, but only for more complex plugins (like one that handles potions or mobs).

**Comment by ghost** [comment]
Can you build me a custom version of yours?

**Comment by ProgrammerDan** [comment]
Sure :).

**Comment by ghost** [comment]
Thanks.

**Comment by ProgrammerDan** [comment]
Try this one: https://github.com/DevotedMC/WorldBorder/releases/tag/1.9.2-unofficial

It's what I've been running on Devoted.
